spring:
  datasource:
    url: jdbc:mysql://10.0.0.200:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Root@mysql1