spring:
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Root@mysql1